import React,{useEffect,useRef,useState} from 'react';
import {Plus,Minus,Maximize,Link2} from 'lucide-react';
export default function Canvas({doc,onChange,onOpen}){
 const host=useRef(),[scale,setScale]=useState(.55),[offset,setOffset]=useState({x:460,y:410}),[connect,setConnect]=useState(null),drag=useRef();
 let data;try{data=JSON.parse(doc.content);if(!Array.isArray(data.nodes))throw Error()}catch{return <div className="empty">Invalid Canvas JSON. Open source mode to repair it.</div>}
 const colors={'1':'#705052','2':'#795f44','3':'#757043','4':'#466450','5':'#435d70','6':'#66517b'};
 function update(d){onChange(JSON.stringify(d,null,'\t'))}
 function fit(){const w=host.current?.clientWidth||800,h=host.current?.clientHeight||650;if(!data.nodes.length)return;const minX=Math.min(...data.nodes.map(n=>n.x)),minY=Math.min(...data.nodes.map(n=>n.y)),maxX=Math.max(...data.nodes.map(n=>n.x+n.width)),maxY=Math.max(...data.nodes.map(n=>n.y+n.height)),s=Math.min(w/(maxX-minX+120),h/(maxY-minY+120),1);setScale(s);setOffset({x:(w-(maxX-minX)*s)/2-minX*s,y:(h-(maxY-minY)*s)/2-minY*s})}
 useEffect(fit,[doc.path]);
 function point(n,side){return {x:n.x+(side==='left'?0:side==='right'?n.width:n.width/2),y:n.y+(side==='top'?0:side==='bottom'?n.height:n.height/2)}}
 function nodeClick(n){if(connect===true){setConnect(n.id);return}if(typeof connect==='string'){if(connect!==n.id)update({...data,edges:[...(data.edges||[]),{id:crypto.randomUUID(),fromNode:connect,fromSide:'right',toNode:n.id,toSide:'left'}]});setConnect(null);return}if(n.type==='file')onOpen(n.file);else if(n.type==='text'){const text=prompt('Card text',n.text);if(text!==null)update({...data,nodes:data.nodes.map(x=>x.id===n.id?{...x,text}:x)})}}
 return <div className="canvas-view" ref={host} onWheel={e=>{if(e.ctrlKey||e.metaKey){setScale(s=>Math.max(.1,Math.min(2,s*(e.deltaY>0?.9:1.1))))}else setOffset(p=>({x:p.x-e.deltaX,y:p.y-e.deltaY}))}} onPointerDown={e=>{if(e.target===host.current){drag.current={pan:true,x:e.clientX,y:e.clientY,xOffset:offset.x,yOffset:offset.y};host.current.setPointerCapture(e.pointerId)}}} onPointerMove={e=>{const d=drag.current;if(!d)return;if(d.pan)setOffset({x:d.xOffset+(e.clientX-d.x),y:d.yOffset+(e.clientY-d.y)});else{const nodes=data.nodes.map(n=>n.id===d.id?{...n,x:d.nx+(e.clientX-d.x)/scale,y:d.ny+(e.clientY-d.y)/scale}:n);update({...data,nodes})}}} onPointerUp={()=>drag.current=null}>
  <div className="canvas-tools"><button onClick={()=>update({...data,nodes:[...data.nodes,{id:crypto.randomUUID(),type:'text',text:'New card',x:(350-offset.x)/scale,y:(220-offset.y)/scale,width:300,height:180}]})}><Plus size={16}/> Card</button><button className={connect?'selected':''} onClick={()=>setConnect(connect?null:true)}><Link2 size={16}/>{connect?'Choose two cards':'Connect'}</button><button onClick={()=>setScale(s=>Math.min(2,s*1.2))}><Plus size={16}/></button><button onClick={()=>setScale(s=>Math.max(.1,s/1.2))}><Minus size={16}/></button><button onClick={fit}><Maximize size={16}/></button><span>{Math.round(scale*100)}%</span></div>
  <div className="canvas-world" style={{transform:`translate(${offset.x}px,${offset.y}px) scale(${scale})`}}><svg className="canvas-edges"><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#77877f"/></marker></defs>{(data.edges||[]).map(e=>{const a=data.nodes.find(n=>n.id===e.fromNode),b=data.nodes.find(n=>n.id===e.toNode);if(!a||!b)return null;const p=point(a,e.fromSide),q=point(b,e.toSide);return <g key={e.id}><line x1={p.x} y1={p.y} x2={q.x} y2={q.y} stroke="#65786d" strokeWidth="2" markerEnd="url(#arrow)"/>{e.label&&<text x={(p.x+q.x)/2} y={(p.y+q.y)/2-8} fill="#999" fontSize="16">{e.label}</text>}</g>})}</svg>{data.nodes.map(n=><div key={n.id} className={'canvas-node '+(n.type==='group'?'group':'')} style={{left:n.x,top:n.y,width:n.width,height:n.height,borderColor:colors[n.color]||n.color||'#555'}}><div className="card-handle" onPointerDown={e=>{e.stopPropagation();drag.current={id:n.id,x:e.clientX,y:e.clientY,nx:n.x,ny:n.y};e.target.setPointerCapture(e.pointerId)}}>{n.type}<button onClick={()=>update({...data,nodes:data.nodes.filter(x=>x.id!==n.id),edges:(data.edges||[]).filter(e=>e.fromNode!==n.id&&e.toNode!==n.id)})}>×</button></div><div className="card-body" onDoubleClick={()=>nodeClick(n)} onClick={()=>connect&&nodeClick(n)}>{n.text||n.label||n.file||n.url}<small>{n.type==='file'?'Double-click to open':'Double-click to edit'}</small></div></div>)}</div>
 </div>
}
