import React,{useEffect,useState} from 'react';
import {Laptop,Tablet,Link2,Copy,Check,RefreshCw,Wifi,ShieldCheck,Unplug,Eye,EyeOff} from 'lucide-react';
import {api} from './api';
export default function DeviceSync({onError}){
 const [status,setStatus]=useState(null),[code,setCode]=useState(''),[join,setJoin]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false),[show,setShow]=useState(false);
 useEffect(()=>{api('syncStatus').then(setStatus).catch(onError);const event=e=>{if(e.detail.name==='sync')setStatus(e.detail.data)};window.addEventListener('vault-event',event);return()=>window.removeEventListener('vault-event',event)},[]);
 async function action(method,args){setBusy(true);try{const s=await api(method,args);setStatus(s);if(s.code){setCode(s.code);setShow(true)}}catch(e){onError(e)}finally{setBusy(false)}}
 async function reveal(){if(show){setShow(false);return}try{const r=await api('syncCode');setCode(r.code);setShow(true)}catch(e){onError(e)}}
 return <><div className="settings-section-title"><h2>Device sync</h2><p>A direct connection. Your files, on your devices.</p></div><section className="sync-hero"><div className="sync-illustration"><Laptop size={35}/><span><i/><i/><i/></span><Tablet size={31}/></div><h3>{status?.paired?'Your private connection':'Keep your devices together.'}</h3><p>Encrypted transfers over your local network. No account, cloud drive, or hosted relay.</p><span className="sync-status"><span className={'local-dot '+(!status?.paired?'inactive':'')}/>{status?.phase||'Checking connection'}</span></section>
 {status?.error&&<div className="inline-error">{status.error}<p>Your files are safe. Vault will retry when the paired device is reachable.</p></div>}
 {!status?.paired?<div className="sync-setup-grid"><section className="settings-card padded"><span className="step-number">1</span><h3>Start on this device</h3><p>Create a private connection for this vault. You’ll get a code to enter on your other device.</p><button className="primary" disabled={busy} onClick={()=>action('syncCreate')}><Link2 size={15}/> Create pairing code</button></section><section className="settings-card padded"><span className="step-number">2</span><h3>Join from another device</h3><p>Open the destination vault, then paste the code from your first device. Existing files are preserved.</p><textarea aria-label="Pairing code" className="pairing-input" autoComplete="off" spellCheck="false" placeholder="AV1.…" value={join} onChange={e=>setJoin(e.target.value)}/><button className="secondary-button" disabled={busy||!join.trim()} onClick={()=>action('syncJoin',{code:join}).then(()=>setJoin(''))}>Pair this vault</button></section></div>:<><section className="settings-card"><div className="setting-row"><div><strong>Paired devices</strong><p>{status.peers?.length?`${status.peers.length} nearby. Sync runs automatically while Vault is open.`:'Open Vault on another paired device to connect.'}</p></div><button className="secondary-button" disabled={busy||!status.peers?.length} onClick={()=>action('syncNow')}><RefreshCw size={14}/> Sync now</button></div>{status.peers?.map(p=><div className="setting-row" key={p.id}><div className="device-row"><Tablet size={21}/><div><strong>{p.name}</strong><p>{p.syncing?'Syncing changes':'Available on your network'}</p></div></div><Wifi size={17}/></div>)}{status.lastSync>0&&<div className="last-sync">Last completed {new Date(status.lastSync*1000).toLocaleString()}</div>}</section><section className="settings-card padded"><h3>Add another device</h3><p>The code grants access to this vault. Enter it only in Vault on your own devices.</p><button className="secondary-button" onClick={reveal}>{show?<EyeOff size={15}/>:<Eye size={15}/>} {show?'Hide pairing code':'Show pairing code'}</button>{show&&<div className="pairing-code"><code>{code}</code><button className="icon-button" title="Copy pairing code" onClick={async()=>{await api('copy',{text:code});setCopied(true);setTimeout(()=>setCopied(false),1500)}}>{copied?<Check size={16}/>:<Copy size={16}/>}</button></div>}</section></>}
 <section className="settings-card padded"><h3><ShieldCheck size={17}/> Designed to preserve your work</h3><p>Offline edits sync when both devices reconnect. Interrupted transfers resume. If both copies change, Vault keeps a visible “sync conflict” copy. Deletions are recoverable in the vault’s hidden recovery folder.</p><p>Documents, attachments, conversations, and bookmarks sync. Appearance, open tabs, and unsaved drafts stay specific to each device. Hidden folders and excluded development folders never transfer.</p><p>Keep Vault open during the first transfer. iOS may suspend connections in the background. Devices need a direct connection; this build discovers them on the same local network.</p></section>
 {status?.paired&&<button className="text-button disconnect" onClick={()=>{if(confirm('Disconnect this device from sync? Local files stay on this device.')){action('syncDisconnect');setShow(false);setCode('')}}}><Unplug size={15}/> Disconnect this device</button>}</>
}
