import {transition} from './motion';
import React,{useState,useEffect,useLayoutEffect,useRef,useMemo,lazy,Suspense} from 'react';
import {createRoot} from 'react-dom/client';
import {Folder,FolderOpen,FileText,Search,PanelLeft,PanelRight,Plus,X,ChevronRight,ChevronLeft,Settings,BookOpen,Code2,Columns2,Network,Star,CalendarDays,Command,Link2,Hash,Clock,MoreHorizontal,ArrowUpRight,Check,RefreshCw,MessageSquare,Shield,SquarePen,File,LayoutDashboard,Table2,Image,Volume2} from 'lucide-react';
import {api,assetURL} from './api';
import Editor from './Editor';import Reader,{prepareReaderForPrint} from './Reader';import Graph from './Graph';import Canvas from './Canvas';import Bases from './Bases';import Chat from './Chat';
import {frontmatter,updateProperties} from './markdown';
import SettingsPage from './Settings';import {applyAppearance,appearanceTokens,defaultAppearance} from './themes';
import './style.css';import 'katex/dist/katex.min.css';
import VaultMark from './VaultMark';import {mergeIncomingState} from './sharedState';
import './product.css';import './workspace.css';import './glass.css';import './reader.css';
import {installViewport} from './viewport';
installViewport();
const PDFReader=lazy(()=>import('./PDFReader'));
const icons={md:FileText,markdown:FileText,pdf:BookOpen,canvas:LayoutDashboard,base:Table2,png:Image,jpg:Image,jpeg:Image,mp3:Volume2,m4a:Volume2};
const day=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function App(){
 const [systemDark,setSystemDark]=useState(()=>matchMedia('(prefers-color-scheme: dark)').matches);
 const [status,setStatus]=useState(null),[state,setState]=useState(null),[folder,setFolder]=useState(''),[items,setItems]=useState([]),[query,setQuery]=useState(''),[results,setResults]=useState([]),[loading,setLoading]=useState(false),[doc,setDoc]=useState(null),[tabs,setTabs]=useState([]),[mode,setMode]=useState('read'),[page,setPage]=useState('home'),[sidebar,setSidebar]=useState(()=>innerWidth>650),[chat,setChat]=useState(false),[inspector,setInspector]=useState(false),[sideMode,setSideMode]=useState('files'),[tags,setTags]=useState([]),[links,setLinks]=useState([]),[outgoing,setOutgoing]=useState([]),[notice,setNotice]=useState(''),[modal,setModal]=useState(''),[rules,setRules]=useState(null),[revisions,setRevisions]=useState([]),[saved,setSaved]=useState(true),[saving,setSaving]=useState(false),[anchor,setAnchor]=useState(''),[commandQuery,setCommandQuery]=useState(''),[searchOffset,setSearchOffset]=useState(0),[fileOffset,setFileOffset]=useState(0),[settingSection,setSettingSection]=useState('appearance');
 function navigate(next){transition(()=>setPage(next));setChat(false);if(innerWidth<=650)setSidebar(false)}
 const folderRef=useRef(folder);folderRef.current=folder;
 const documentRequest=useRef(0),docRef=useRef(),stateRef=useRef(),savedContent=useRef(''),savePromise=useRef(),pendingState=useRef(),stateTimer=useRef(),searchRef=useRef(),commandRef=useRef();docRef.current=doc;stateRef.current=state;
 const fail=e=>{setNotice(e?.message||String(e))};
 useEffect(()=>{const changed=async e=>{if(e.detail.name!=="files")return;api('list',{path:folderRef.current}).then(setItems).catch(()=>{});const d=docRef.current;if(d&&e.detail.data.paths.includes(d.path)){if(d.content===savedContent.current){try{const generation=documentRequest.current;const next=await api('read',{path:d.path});if(generation!==documentRequest.current||docRef.current?.path!==d.path||docRef.current?.content!==d.content||savedContent.current!==d.content)return;savedContent.current=next.content||'';docRef.current=next;setDoc(next);setSaved(true)}catch(err){fail(err)}}else setNotice('This document changed outside Vault. Your draft is retained. Save as a copy or reload before replacing it.')}};window.addEventListener('vault-event',changed);return()=>window.removeEventListener('vault-event',changed)},[]);
 useLayoutEffect(()=>{const apply=()=>{const mode=applyAppearance(state?.appearance||defaultAppearance);api('appearance',{mode,background:getComputedStyle(document.documentElement).getPropertyValue('--bg').trim(),theme:(state?.appearance||defaultAppearance).theme,matchIcon:state?.appearance?.matchIcon!==false}).catch(()=>{})};apply();const media=matchMedia('(prefers-color-scheme: dark)');const changed=()=>{setSystemDark(media.matches);apply()};media.addEventListener('change',changed);return()=>media.removeEventListener('change',changed)},[JSON.stringify(state?.appearance)]);
 useEffect(()=>{const listener=async e=>{if(e.detail.name==='sharedState'){try{const incoming=await api('state');setState(s=>mergeIncomingState(s,incoming))}catch(e){fail(e)}}};window.addEventListener('vault-event',listener);api('platform').then(p=>{document.documentElement.dataset.platform=p.name}).catch(()=>{});return()=>window.removeEventListener('vault-event',listener)},[]);
 async function refresh(){const s=await api('status');setStatus(s);return s}
 async function switchVault(){
  try{await save();if(stateRef.current)await api('saveState',{...stateRef.current,tabs,active:docRef.current?.path||null});
   documentRequest.current++;setLoading(false);setState(null);stateRef.current=null;setDoc(null);docRef.current=null;savedContent.current='';setSaved(true);setTabs([]);setFolder('');setItems([]);setResults([]);navigate('home');setQuery('');
   await new Promise(requestAnimationFrame);
   try{await api('chooseVault')}catch(e){if(e.message!=='Cancelled')throw e}
   await boot();
  }catch(e){fail(e);await boot()}
 }
 async function boot(){try{const s=await refresh();if(s.connected===false)return;const savedState=await api('state');setState(savedState);setTabs(savedState.tabs||[]);setItems(await api('list'));setResults(await api('search'));if(savedState.active){await openDoc(savedState.active,false,savedState)}}catch(e){fail(e)}}
 useEffect(()=>{api('initialize').then(boot).catch(fail);const timer=setInterval(()=>refresh().catch(()=>{}),2200);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(!state)return;pendingState.current={...state,tabs,active:doc?.path||null};if(!stateTimer.current)stateTimer.current=setTimeout(()=>{stateTimer.current=null;const latest=pendingState.current;pendingState.current=null;if(latest)api('saveState',latest).catch(fail)},500)},[state,tabs,doc?.path]);
 useEffect(()=>()=>{clearTimeout(stateTimer.current);if(pendingState.current)api('saveState',pendingState.current).catch(()=>{})},[]);
 useEffect(()=>{if(!status||status.connected===false)return;api('list',{path:folder}).then(setItems).catch(fail);setFileOffset(0)},[folder,status?.running===false]);
 useEffect(()=>{const timer=setTimeout(async()=>{if(!state)return;setLoading(true);const key=query;searchRef.current=key;try{const rows=await api('search',{query:key});if(searchRef.current===key){setResults(rows);setSearchOffset(0)}}catch(e){fail(e)}finally{setLoading(false)}},220);return()=>clearTimeout(timer)},[query,state!==null]);
 useEffect(()=>{if(!doc)return;api('backlinks',{path:doc.path}).then(setLinks).catch(fail);api('outgoing',{path:doc.path}).then(setOutgoing).catch(fail)},[doc?.path,saved]);
 useEffect(()=>{if(sideMode==='tags')api('tags').then(setTags).catch(fail)},[sideMode,status?.count]);
 useEffect(()=>{if(!doc||saved||!['md','markdown','txt','canvas','base'].includes(doc.ext))return;const timer=setTimeout(()=>save().catch(()=>{}),1200);return()=>clearTimeout(timer)},[doc?.content,saved]);
 async function save(){
  if(savePromise.current){await savePromise.current;if(docRef.current?.content===savedContent.current)return true;}
  const d=docRef.current;if(!d?.content&&d?.content!=='')return true;if(d.content===savedContent.current){setSaved(true);return true}
  setSaving(true);const promise=(async()=>{try{const value=await api('save',{path:d.path,content:d.content,revision:d.revision});savedContent.current=d.content;if(docRef.current?.content===d.content)setState(s=>({...s,draft:null}));if(docRef.current?.path===d.path){setDoc(current=>({...current,revision:value.revision}));docRef.current={...docRef.current,revision:value.revision};setSaved(docRef.current.content===d.content)}setNotice('');return true}catch(e){fail(e);throw e}finally{setSaving(false);savePromise.current=null}})();savePromise.current=promise;return promise;
 }
 function edit(content){setDoc(d=>({...d,content}));setSaved(content===savedContent.current);setState(s=>({...s,draft:{path:docRef.current.path,content,revision:docRef.current.revision}}))}
 async function openDoc(path,add=true,initialState){const generation=++documentRequest.current;try{await save();if(generation!==documentRequest.current)return;setLoading(true);const data=await api('read',{path});if(generation!==documentRequest.current)return;const draft=(initialState||stateRef.current)?.draft;if(draft?.path===path&&draft.content!==data.content){data.content=draft.content;data.revision=draft.revision;setSaved(false);savedContent.current='\u0000'}else{savedContent.current=data.content||'';setSaved(true)}setDoc(data);docRef.current=data;navigate('document');setAnchor('');if(add)setTabs(t=>t.includes(path)?t:[...t,path]);if(initialState&&!tabs.includes(path))setTabs(t=>t.includes(path)?t:[...t,path]);}catch(e){if(generation===documentRequest.current)fail(e)}finally{if(generation===documentRequest.current)setLoading(false)}}
 async function link(target){const [file,...fragment]=target.split('#');if(!file&&doc){setAnchor(fragment.join('#'));return}try{const rows=await api('resolve',{target,path:docRef.current?.path||''});if(rows.length===1){await openDoc(rows[0].path);setAnchor(fragment.join('#'))}else if(rows.length>1){setResults(rows);setQuery('');navigate('search');setNotice('Several documents share this title. Choose the intended path.')}else{if(confirm('No document exists for '+file+'. Create it?'))await create(file.endsWith('.md')?file:file+'.md')}}catch(e){fail(e)}}
 async function create(path,content){if(!path)path=prompt('New document path',folder?folder+'/Untitled.md':'Untitled.md');if(!path)return;if(!/\.(md|canvas|base|txt)$/i.test(path))path+='.md';try{await save();const existing=await api('resolve',{target:path});if(existing.some(r=>r.path===path))throw Error('That document already exists');const body=content??(path.endsWith('.canvas')?'{"nodes":[],"edges":[]}':path.endsWith('.base')?'filters:\n  and:\n    - file.inFolder("'+folder+'")\nviews:\n  - type: table\n    name: Table\n    order:\n      - file.name\n':'# '+path.split('/').pop().replace(/\.md$/,'')+'\n\n');await api('save',{path,content:body});setState(s=>({...s,draft:null}));await openDoc(path);setMode(path.endsWith('.md')?'edit':'read');setItems(await api('list',{path:folder}));refresh()}catch(e){fail(e)}}
 async function daily(){const path=(state?.dailyFolder||'Daily notes')+'/'+day()+'.md';try{const rows=await api('resolve',{target:path});if(rows.some(r=>r.path===path))await openDoc(path);else await create(path,'# '+day()+'\n\n')}catch(e){fail(e)}}
 async function printDocument(){let restore=()=>{};try{if(docRef.current?.ext==='pdf')return await api('openNative',{path:docRef.current.path});restore=await prepareReaderForPrint();return await api('print')}catch(e){fail(e)}finally{restore()}}
 async function template(){try{const rows=await api('list',{path:state?.templatesFolder||'Templates'});setResults(rows.filter(r=>!r.directory));setModal('templates')}catch(e){fail(e)}}
 async function insertTemplate(path){try{const t=await api('read',{path}),text=t.content.replace(/\{\{date\}\}/g,day()).replace(/\{\{time\}\}/g,new Date().toLocaleTimeString()).replace(/\{\{title\}\}/g,doc?.title||'');edit((doc?.content||'')+'\n'+text);setMode('edit');setModal('')}catch(e){fail(e)}}
 const commands=[['New note','⌘N',()=>create()],['Open daily note','',daily],['New folder','',async()=>{const path=prompt('Folder path',folder?folder+'/':'');if(path)try{await api('folder',{path});setItems(await api('list',{path:folder}))}catch(e){fail(e)}}],['New canvas','',()=>create((folder?folder+'/':'')+'Untitled.canvas')],['New base','',()=>create((folder?folder+'/':'')+'Untitled.base')],['Insert template','',template],['Read document','⌘E',()=>setMode('read')],['Edit source','⌘E',()=>setMode('edit')],['Split editor and preview','',()=>setMode('split')],['Local graph','',()=>navigate('localgraph')],['Entire library graph','',()=>navigate('graph')],['File recovery','',async()=>{if(doc){setRevisions(await api('recovery',{path:doc.path}));setModal('recovery')}}],['Reveal in Finder','',()=>doc&&api('reveal',{path:doc.path})],['Export / print PDF','',()=>printDocument()],['Recheck changed files','',()=>api('scan').then(refresh).catch(fail)],['Open another vault','',switchVault],['Library settings','⌘,',()=>settings()]];
 useEffect(()=>{const onKey=e=>{if(!(e.metaKey||e.ctrlKey))return;if(e.key==='s'){e.preventDefault();save().catch(()=>{})}else if(e.key==='n'){e.preventDefault();create()}else if(e.key==='o'||e.key==='p'){e.preventDefault();setCommandQuery('');setModal(e.key==='p'?'commands':'switcher')}else if(e.key==='k'){e.preventDefault();navigate('search');setTimeout(()=>document.getElementById('library-search')?.focus(),30)}else if(e.key==='e'){e.preventDefault();setMode(m=>m==='read'?'edit':'read')}else if(e.key===','){e.preventDefault();settings()}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[doc,state,folder]);
 async function settings(section='appearance'){try{setRules(await api('rules'));setSettingSection(typeof section==='string'?section:'appearance');navigate('settings');setChat(false);setModal('')}catch(e){fail(e)}}
 function bookmark(){if(!doc)return;setState(s=>({...s,bookmarkChanges:{...(s.bookmarkChanges||{}),[doc.path]:{present:!(s.bookmarks||[]).includes(doc.path),modified:Date.now()}},bookmarks:(s.bookmarks||[]).includes(doc.path)?s.bookmarks.filter(p=>p!==doc.path):[...(s.bookmarks||[]),doc.path]}))}
 async function closeTab(path){if(doc?.path===path){try{await save()}catch{return}const remaining=tabs.filter(p=>p!==path);setTabs(remaining);if(remaining.length)openDoc(remaining.at(-1),false);else{documentRequest.current++;setDoc(null);docRef.current=null;setLoading(false);navigate('home')}}else setTabs(t=>t.filter(p=>p!==path))}
 async function changeProperty(key){const props=frontmatter(doc.content).properties,old=props[key],value=prompt('Property: '+key,Array.isArray(old)?JSON.stringify(old):String(old??''));if(value===null)return;try{const {parse}=await import('yaml');props[key]=parse(value);edit(updateProperties(doc.content,props))}catch(e){fail(e)}}
 const {properties,headings,wordCount}=useMemo(()=>{const content=doc?.content||'',headings=[];for(const match of content.matchAll(/^(#{1,6}) (.+)$/gm)){headings.push({depth:match[1].length,title:match[2]});if(headings.length===150)break}let wordCount=0;const words=/\S+/g;while(words.exec(content))wordCount++;return{properties:frontmatter(content).properties,headings,wordCount}},[doc?.content]);
 const isText=doc&&['md','markdown','txt','canvas','base'].includes(doc.ext),bookmarked=state?.bookmarks?.includes(doc?.path);
 const listRows=(rows)=>rows.map(r=>{const Icon=r.directory?Folder:(icons[r.ext]||File);return <button key={r.path} className={'file-row '+(r.path===doc?.path?'active':'')} title={r.path} onClick={()=>r.directory?setFolder(r.path):openDoc(r.path)}><Icon size={15}/><span>{r.title}</span>{r.directory&&<ChevronRight size={12}/>}</button>});
 if(!status)return <div className="onboarding"><img className="onboarding-icon" src="vault://app/vault-icon.png" alt=""/><h1>Opening your workspace.</h1><p>Your files are staying right where they belong.</p><button className="secondary-button" onClick={async()=>{try{await api('chooseVault');await boot()}catch(e){fail(e)}}}>Choose a vault folder</button>{notice&&<p>{notice}</p>}</div>;
 if(status?.connected===false)return <div className="onboarding"><img className="onboarding-icon" src="vault://app/vault-icon.png" alt="Archii Vault"/><h1>Your research.<br/>Your files.</h1><p>A private workspace for the things you’re discovering.<br/>Open an existing vault. Everything stays on your drive.</p><button className="primary" onClick={async()=>{try{await api('chooseVault');await boot()}catch(e){fail(e)}}}><FolderOpen size={17}/> Open a vault</button><button className="secondary-button" onClick={async()=>{try{await api('createLocalVault');await boot()}catch(e){fail(e)}}}>Create a local vault</button><small>{notice||'No account. No cloud upload. No import required.'}</small></div>;
 const palette=appearanceTokens(state?.appearance);
 return <div className="app" style={palette} data-sidebar={sidebar?"open":"closed"} data-page={page}>
  {sidebar&&<button className="panel-scrim" aria-label="Close navigation" onClick={()=>setSidebar(false)}/> }
  {<aside className="sidebar" style={{backgroundColor:palette['--sidebar']}} aria-hidden={!sidebar} inert={!sidebar?true:undefined}><div className="brand"><VaultMark/><strong>Vault</strong><button title="Hide sidebar" onClick={()=>setSidebar(false)}><PanelLeft size={17}/></button></div><button className="vault-picker" onClick={()=>commands.find(c=>c[0]==='Open another vault')[2]()}><FolderOpen size={16}/><span>{status?.name||'Opening…'}</span><ChevronRight size={13}/></button><nav aria-label="Workspace navigation"><button title="Library" aria-label="Library" className={page==='home'||page==='document'?'selected':''} onClick={()=>navigate('home')}><BookOpen size={18}/></button><button title="Search your library" aria-label="Search your library" className={page==='search'?'selected':''} onClick={()=>{navigate('search');setTimeout(()=>document.getElementById('library-search')?.focus(),30)}}><Search size={18}/></button><button title="Conversations" aria-label="Conversations" onClick={()=>navigate('chat')}><MessageSquare size={18}/></button><button title="Daily note" aria-label="Daily note" onClick={daily}><CalendarDays size={18}/></button><button title="Graph" aria-label="Graph" onClick={()=>navigate('graph')} className={page==='graph'?'selected':''}><Network size={18}/></button></nav><div className="section-tabs"><button className={sideMode==='files'?'selected':''} onClick={()=>setSideMode('files')}>Files</button><button title="Bookmarks" className={sideMode==='bookmarks'?'selected':''} onClick={()=>setSideMode('bookmarks')}><Star size={14}/></button><button title="Tags" className={sideMode==='tags'?'selected':''} onClick={()=>setSideMode('tags')}><Hash size={14}/></button><button title="New note" onClick={()=>create()}><Plus size={15}/></button></div>
   {sideMode==='files'&&<>{folder&&<div className="folder-trail"><button title={'Back to '+(folder.split('/').slice(0,-1).pop()||status.name)} onClick={()=>setFolder(folder.split('/').slice(0,-1).join('/'))}><ChevronLeft size={15}/></button><span title={folder}>{folder.split('/').pop()}</span></div>}<div className="file-list">{listRows(items)}{items.filter(i=>!i.directory).length>=200&&<button className="more-files" onClick={async()=>{const offset=fileOffset+200;const more=await api('list',{path:folder,offset});setItems(i=>[...i,...more]);setFileOffset(offset)}}>Load more files</button>}</div></>}
   {sideMode==='bookmarks'&&<div className="file-list">{listRows((state?.bookmarks||[]).map(path=>({path,title:path.split('/').pop().replace(/\.md$/,''),ext:path.split('.').pop()})))}{!state?.bookmarks?.length&&<p className="muted side-hint">Star a document to keep it here.</p>}</div>}
   {sideMode==='tags'&&<div className="file-list">{tags.map(t=><button className="file-row" key={t.tag} onClick={()=>{setQuery('tag:'+t.tag);navigate('search')}}><Hash size={13}/><span>{t.tag}</span><small>{t.count}</small></button>)}</div>}
   <footer><div className="index-status"><span className={'local-dot '+(status?.running?'pulse':'')}/><div><strong>{status?.running?'Indexing locally':'On this device'}</strong><small>{(status?.count||0).toLocaleString()} documents{status?.running?' · '+(status.visited||0).toLocaleString()+' scanned':''}</small></div></div><div className="sidebar-bottom"><button title="Settings" onClick={settings}><Settings size={17}/></button><span>Private by default</span><button title="Command palette" onClick={()=>setModal('commands')}><Command size={16}/></button></div></footer>
  </aside>}
  <main className="workspace"><div className="titlebar">{!sidebar&&<button title="Show sidebar" onClick={()=>{setSidebar(true);if(document.documentElement.dataset.platform==='ios'){setInspector(false);setChat(false)}}}><PanelLeft size={17}/></button>}<span className="breadcrumb">{page==='document'?doc?.path.split('/').slice(0,-1).join(' / ')||status?.name:page==='search'?'Search your library':page==='settings'?'Settings':page==='chat'?'Conversations':page.includes('graph')?'Connections':'Your workspace'}</span><div className="titlebar-actions"><button title="New note" onClick={()=>create()}><SquarePen size={17}/></button><button title="Show document details" className={inspector?'selected':''} onClick={()=>{setInspector(x=>!x);setChat(false);if(innerWidth<=1100||document.documentElement.dataset.platform==='ios')setSidebar(false)}}><PanelRight size={17}/></button>{page!=='chat'&&<button className={'chat-toggle '+(chat?'selected':'')} onClick={()=>{navigate('chat');setInspector(false)}}><MessageSquare size={16}/><span>Ask anything</span></button>}</div></div>
   {tabs.length>0&&page!=='settings'&&page!=='chat'&&<div className="document-tabs">{tabs.map(path=><button key={path} className={doc?.path===path&&page==='document'?'selected':''} onClick={()=>openDoc(path,false)}><FileText size={13}/><span>{path.split('/').pop().replace(/\.md$/,'')}</span><span className="tab-close" role="button" tabIndex={0} onClick={e=>{e.stopPropagation();closeTab(path)}}><X size={12}/></span></button>)}</div>}
   {notice&&<div className="notice global-notice"><span>{notice}</span><button onClick={()=>setNotice('')}><X size={14}/></button></div>}
   <div className="document-space">
    <section className="main-pane" data-stage={page}>
     {page==='settings'&&state&&<SettingsPage key={settingSection} initial={settingSection} state={state} setState={setState} rules={rules} setRules={setRules} status={status} onBack={()=>navigate(doc?'document':'home')} onRefresh={refresh} onError={fail}/>}
     {page==='chat'&&state&&<Chat fullPage initialDraft={state.chatDraft||''} onDraft={chatDraft=>setState(s=>({...s,chatDraft}))} doc={doc} chats={state.chats||[]} setChats={chats=>setState(s=>({...s,chats}))} activeId={state.activeChat} onActive={activeChat=>setState(s=>({...s,activeChat}))} preferences={state.ai} onSettings={settings} onClose={()=>{navigate(doc?'document':'home');setSidebar(true)}} onLink={link}/>}

     {page==='home'&&<div className="home"><div className="eyebrow">YOUR PRIVATE LIBRARY</div><h1>Room for every thought.</h1><p className="home-subtitle">Your notes, documents, and discoveries.<br/>Connected, searchable, and entirely yours.</p><div className="home-search" onClick={()=>{navigate('search');setTimeout(()=>document.getElementById('library-search')?.focus(),30)}}><Search size={19}/><span>Find something in your research</span><kbd>⌘K</kbd></div><div className="home-actions"><button onClick={()=>create()}><SquarePen size={17}/> New note</button><button onClick={daily}><CalendarDays size={17}/> Today’s note</button><button onClick={()=>navigate('chat')}><MessageSquare size={17}/> Start a conversation</button></div><div className="recent-heading"><span>Recently changed</span><small>{(status?.count||0).toLocaleString()} documents in your library</small></div><div className="recent-list">{results.slice(0,8).map(r=>{const Icon=icons[r.ext]||File;return <button key={r.path} onClick={()=>openDoc(r.path)}><div className="recent-icon"><Icon size={18}/></div><div><strong>{r.title}</strong><small>{r.path.split('/').slice(0,-1).join(' / ')}</small></div><ArrowUpRight size={15}/></button>})}</div><div className="home-foot"><Shield size={14}/><span>Files stay in your vault. Development folders stay out of the way.</span></div></div>}
     {page==='search'&&<div className="search-page"><div className="search-input"><Search size={20}/><input id="library-search" placeholder='Search text, path:"Projects", tag:research…' value={query} onChange={e=>setQuery(e.target.value)} autoFocus/>{query&&<button onClick={()=>setQuery('')}><X size={17}/></button>}</div><div className="view-caption">{loading?'Searching…':results.length+' results'} · Indexed text and document titles</div><div className="search-results">{results.map(r=><button key={r.path} onClick={()=>openDoc(r.path)}><strong><FileText size={16}/>{r.title}</strong><small>{r.path}</small>{r.snippet&&<p>{r.snippet}</p>}</button>)}{!results.length&&!loading&&<div className="empty">No matching documents. Try fewer terms or a path filter.</div>}{results.length>=80&&<button onClick={async()=>{const offset=searchOffset+80;setResults(r=>r);const more=await api('search',{query,offset});setResults(r=>[...r,...more]);setSearchOffset(offset)}}>Load more results</button>}</div></div>}
     {(page==='graph'||page==='localgraph')&&<Graph path={page==='localgraph'?doc?.path||'':''} onOpen={openDoc}/>}
     {page==='document'&&doc&&<><div className="document-toolbar"><div className="doc-identity"><span>{doc.ext.toUpperCase()}</span><h2 title={doc.path}>{doc.title}</h2></div><div><button title="Bookmark" className={bookmarked?'starred':''} onClick={bookmark}><Star size={15}/></button>{isText&&<div className="view-switch"><button title="Reading view" className={mode==='read'?'selected':''} onClick={()=>setMode('read')}><BookOpen size={15}/></button><button title="Source mode" className={mode==='edit'?'selected':''} onClick={()=>setMode('edit')}><Code2 size={15}/></button><button title="Split preview" className={mode==='split'?'selected':''} onClick={()=>setMode('split')}><Columns2 size={15}/></button></div>}<button title="Document actions" onClick={()=>setModal('actions')}><MoreHorizontal size={19}/></button></div></div>
      {isText&&mode!=='edit'&&Object.keys(properties).length>0&&<details className="properties"><summary>Properties <span>{Object.keys(properties).length}</span></summary><div>{Object.entries(properties).map(([key,value])=><button key={key} onClick={()=>changeProperty(key)}><span>{key}</span><strong>{typeof value==='object'?JSON.stringify(value):String(value??'')}</strong></button>)}</div></details>}
      <div className={'document-body '+(mode==='split'?'split':'')}>
       {isText&&mode!=='read'&&<Editor key={doc.path} path={doc.path} value={doc.content} onChange={edit} onSave={()=>save().catch(()=>{})}/>}
       {isText&&mode!=='edit'&&(doc.ext==='canvas'?<Canvas doc={doc} onChange={edit} onOpen={openDoc}/>:doc.ext==='base'?<Bases doc={doc} onOpen={openDoc} onError={fail}/>:<Reader content={doc.content} path={doc.path} onLink={link} anchor={anchor} onTaskToggle={(index,checked)=>{let n=0;const text=doc.content.replace(/^(\s*[-*+] )\[[ xX]\]/gm,(match,prefix)=>n++===index?prefix+'['+(checked?'x':' ')+']':match);edit(text)}}/>)}
       {!isText&&(['png','jpg','jpeg','gif','svg','webp','heic'].includes(doc.ext)?<div className="image-view"><img src={assetURL(doc.path)}/></div>:doc.ext==='pdf'?<Suspense fallback={<div className="empty">Opening PDF…</div>}><PDFReader path={doc.path} title={doc.title}/></Suspense>:['mp3','m4a','wav'].includes(doc.ext)?<div className="empty"><audio src={assetURL(doc.path)} controls/></div>:['mp4','mov'].includes(doc.ext)&&doc.size<80000000?<video src={assetURL(doc.path)} controls/>:<div className="native-document"><BookOpen size={44}/><h2>{doc.title}</h2><p>{(doc.size/1000000).toFixed(1)} MB · {doc.ext.toUpperCase()}</p><button className="primary" onClick={()=>api('openNative',{path:doc.path})}>Open in native document viewer <ArrowUpRight size={16}/></button><small>This attachment is loaded only when you open it.</small></div>)}
      </div><div className="document-status"><span>{isText?`${wordCount.toLocaleString()} words`:`${(doc.size/1000000).toFixed(1)} MB`}</span><span>{isText?(saving?'Saving…':saved?<><Check size={12}/> Saved locally</>:'Unsaved changes'):'Local attachment'}</span></div></>}
    </section>
    {inspector&&page!=='settings'&&page!=='chat'&&<aside className="inspector"><div className="inspector-heading"><h3>Document details</h3><button className="icon-button" title="Close document details" onClick={()=>setInspector(false)}><X size={18}/></button></div>{doc?<><div className="detail-heading">OUTLINE</div>{headings.slice(0,150).map((h,i)=><button className="outline-item" key={i} style={{paddingLeft:12+(h.depth-1)*10}} onClick={()=>{setMode('read');setAnchor(h.title)}}>{h.title}</button>)}<div className="detail-heading">BACKLINKS · {links.length}</div>{links.map(l=><button className="detail-link" key={l.path} onClick={()=>openDoc(l.path)}><Link2 size={13}/>{l.title}</button>)}<div className="detail-heading">OUTGOING · {outgoing.length}</div>{outgoing.map(l=><button className="detail-link" key={l.target} onClick={()=>link(l.target)}>{l.target}</button>)}<button className="local-graph-button" onClick={()=>navigate('localgraph')}><Network size={14}/> Explore local graph</button></>:<p className="muted">Open a document to see its connections.</p>}</aside>}
   </div>
  </main>
  {chat&&state&&page!=='chat'&&<Chat activeId={state.activeChat} onActive={activeChat=>setState(s=>({...s,activeChat}))} preferences={state.ai} onSettings={settings} onExpand={()=>{setChat(false);navigate('chat');setSidebar(false)}} doc={doc} chats={state.chats||[]} setChats={chats=>setState(s=>({...s,chats}))} onClose={()=>setChat(false)} onLink={link}/>}
  {modal&&<div className="modal-scrim" onClick={()=>setModal('')}><div className={'modal '+(modal==='settings'?'settings-modal':'')} onClick={e=>e.stopPropagation()}><header><h2>{{commands:'Command palette',switcher:'Quick switcher',actions:'Document actions',settings:'Library settings',recovery:'File recovery',templates:'Insert template'}[modal]}</h2><button onClick={()=>setModal('')}><ChevronLeft size={18}/></button></header>
   {(modal==='commands'||modal==='switcher')&&<><input autoFocus className="command-input" placeholder={modal==='commands'?'Type a command…':'Search document names…'} value={commandQuery} onChange={async e=>{setCommandQuery(e.target.value);if(modal==='switcher')setResults(await api('search',{query:'file:'+e.target.value}))}}/>{modal==='commands'?commands.filter(c=>c[0].toLowerCase().includes(commandQuery.toLowerCase())).map(c=><button className="command-item" key={c[0]} onClick={()=>{setModal('');c[2]()}}>{c[0]}<kbd>{c[1]}</kbd></button>):results.map(r=><button className="command-item" key={r.path} onClick={()=>{setModal('');openDoc(r.path)}}><span>{r.title}<small>{r.path}</small></span></button>)}</>}
   {modal==='actions'&&<>{[['Save',()=>save()],['Rename / move document',async()=>{const oldPath=doc.path,destination=prompt('New path (links will be updated)',oldPath);if(!destination||destination===oldPath)return;await save();await api('move',{path:oldPath,destination,revision:docRef.current.revision});setState(s=>({...s,draft:null,bookmarks:(s.bookmarks||[]).map(p=>p===oldPath?destination:p)}));savedContent.current=docRef.current.content;setTabs(t=>t.map(p=>p===oldPath?destination:p));await openDoc(destination,false);setItems(await api('list',{path:folder}))}],['Add property',()=>{const key=prompt('Property name');if(key)changeProperty(key)}],['File recovery',commands.find(c=>c[0]==='File recovery')[2]],['Insert template',template],['Reveal in Finder',()=>api('reveal',{path:doc.path})],['Print / export PDF',()=>printDocument()],['Save a copy',async()=>{const path=prompt('New path',doc.path.replace(/\.([^.]+)$/,' copy.$1'));if(path)await create(path,doc.content)}],['Move to local trash',async()=>{if(confirm('Move this document to Vault’s recoverable local trash?')){await save();await api('trash',{path:doc.path,revision:docRef.current.revision});setTabs(t=>t.filter(p=>p!==doc.path));setDoc(null);navigate('home');refresh()}}]].map(([label,fn])=><button className="command-item" key={label} onClick={()=>{setModal('');Promise.resolve(fn()).catch(fail)}}>{label}</button>)}</>}
   {modal==='templates'&&results.map(r=><button key={r.path} className="command-item" onClick={()=>insertTemplate(r.path)}>{r.title}</button>)}
   {modal==='recovery'&&<><p className="muted">Saved versions before edits. Restore opens a draft for review.</p>{revisions.map(r=><button className="command-item" key={r.id} onClick={async()=>{const text=await api('recoveryRead',{path:doc.path,id:r.id});edit(text);setMode('edit');setModal('')}}>{new Date(Number(r.id.split('-')[0])).toLocaleString()}<small>{r.size.toLocaleString()} bytes</small></button>)}{!revisions.length&&<p>No prior versions yet.</p>}</>}
   {modal==='settings'&&rules&&<><section><h3>Private, portable files</h3><p>{status?.root}</p><p>Your documents stay in this folder. Bookmarks, conversations, and recovery copies live in the hidden <code>.archii-vault</code> folder. Copy the whole folder, including hidden files, to take them with you. The disposable search index can rebuild on another device.</p></section><section><h3>Folders the library skips</h3><p>Hidden folders are always excluded. These directory names are excluded at every depth:</p><textarea value={rules.excludedDirectories.join('\n')} onChange={e=>setRules({...rules,excludedDirectories:e.target.value.split('\n').map(s=>s.trim()).filter(Boolean)})}/><label>Additional paths relative to the vault</label><textarea value={rules.excludedPaths.join('\n')} placeholder="One folder path per line" onChange={e=>setRules({...rules,excludedPaths:e.target.value.split('\n').map(s=>s.trim()).filter(Boolean)})}/><button className="primary" onClick={async()=>{await api('saveRules',rules);setModal('');api('scan').then(refresh).catch(fail)}}>Save rules and refresh library</button></section><section><h3>Writing</h3><label>Daily notes folder<input value={state.dailyFolder||'Daily notes'} onChange={e=>setState(s=>({...s,dailyFolder:e.target.value}))}/></label><label>Templates folder<input value={state.templatesFolder||'Templates'} onChange={e=>setState(s=>({...s,templatesFolder:e.target.value}))}/></label></section><section><h3>Device sync</h3><p>This build operates on local files. Cross-device synchronization is not connected. No account or cloud service receives this library.</p></section></>}
  </div></div>}
 </div>
}
applyAppearance(defaultAppearance);
class RootBoundary extends React.Component {
 constructor(props){super(props);this.state={error:null}}
 static getDerivedStateFromError(error){return {error}}
 componentDidCatch(error){api('logError',{message:error.message}).catch(()=>{})}
 render(){return this.state.error?<div className="onboarding"><h1>Let’s reopen your workspace.</h1><p>The interface hit an unexpected error. Your files remain on disk.</p><code>{this.state.error.message}</code><button className="primary" onClick={()=>location.reload()}>Reopen workspace</button></div>:this.props.children}
}
createRoot(document.getElementById('root')).render(<RootBoundary><App/></RootBoundary>);
